name: emutravel
description: ""

publish_to: 'none'

version: 1.1.0+1100

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  http: ^1.6.0
  crypto: ^3.0.7
  clipboard: ^3.0.14
  android_intent_plus: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/